# Generated by Django 5.1.4 on 2024-12-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anneescolaire',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='anneescolaire',
            name='date_fin',
        ),
    ]
