# Generated by Django 5.1.4 on 2024-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_remove_anneescolaire_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(max_length=45),
        ),
    ]
