# Generated by Django 5.1.4 on 2024-12-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_alter_paiement_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='utitlisateur',
            new_name='utilisateur',
        ),
    ]
