# Generated by Django 5.1.4 on 2025-01-17 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_rename_utitlisateur_paiement_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
