# Generated by Django 5.1.4 on 2025-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_anneescolaire_date_debut_anneescolaire_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(auto_now_add=True),
        ),
    ]
