# Generated by Django 5.1.4 on 2025-01-22 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_alter_inscription_date_inscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classe',
            new_name='Formation',
        ),
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='AnneeScolaire',
            new_name='School_year',
        ),
        migrations.RenameModel(
            old_name='Eleve',
            new_name='Student',
        ),
    ]
