# Generated by Django 5.1.4 on 2025-01-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_rename_classe_formation_rename_paiement_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('cloturee', 'Cloturée')], default='active', max_length=8),
        ),
    ]
