# Generated by Django 5.1.4 on 2025-01-22 12:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_alter_school_year_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='klemat', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+23599777185', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
