# Generated by Django 5.1.4 on 2025-01-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_student_address_student_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='parent_contact',
        ),
    ]
