# Generated by Django 5.1.4 on 2025-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0010_rename_contact_student_parent_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='abd@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
