# Generated by Django 5.1.4 on 2025-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espece'), ('virement', 'Virement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='motif',
            field=models.CharField(choices=[('inscriptions', 'Inscription'), ('mensuel', 'Mensuel'), ('tranche1', '1er Tranche'), ('tranche2', '2nd Tranche'), ('Annuel', 'Annuel')], max_length=30),
        ),
    ]
