# Generated by Django 5.1.4 on 2025-01-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_alter_payment_mode_paiement_alter_payment_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='frais_inscription',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='mensualite',
            field=models.DecimalField(decimal_places=2, default=12000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='tranche1',
            field=models.DecimalField(decimal_places=2, default=125000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='tranche2',
            field=models.DecimalField(decimal_places=2, default=55000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='statut',
            field=models.CharField(default='invalide', max_length=20),
        ),
    ]
