# Generated by Django 5.1.4 on 2025-01-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0013_formation_frais_inscription_formation_mensualite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='statut',
        ),
        migrations.AddField(
            model_name='formation',
            name='tranche3',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='incomplet', max_length=12),
        ),
    ]
