# Generated by Django 5.1.4 on 2025-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0014_archive_payment_remove_payment_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='incomplet', max_length=20),
        ),
    ]
