# Generated by Django 5.1.4 on 2025-02-15 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0015_alter_inscription_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=30)),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('numero_recu', models.CharField(max_length=12)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=45)),
                ('motif_edition', models.CharField(max_length=200)),
                ('date_archive', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.inscription')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='caisse.payment')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
