# Generated by Django 5.1.4 on 2025-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0016_archive_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('non_inscrit', 'Non Inscrit'), ('inscrit', 'Inscrit'), ('termine', 'Terminé')], default=('non_inscrit', 'Non Inscrit'), max_length=20),
        ),
    ]
