# Generated by Django 5.1.4 on 2025-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0017_alter_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('non_inscrit', 'Non Inscrit'), ('inscrit', 'Inscrit'), ('termine', 'Terminé')], default=('non_inscrit', 'Non Inscrit'), max_length=125),
        ),
    ]
