# Generated by Django 5.1.4 on 2025-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0018_alter_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('cloturee', 'Cloturée')], default='Active', max_length=8),
        ),
    ]
