# Generated by Django 5.1.4 on 2025-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0019_alter_school_year_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='libelle',
            field=models.CharField(max_length=12),
        ),
    ]
